version: 0.2
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file template.yml --s3-bucket https://s3.us-east-2.amazonaws.com --output-template-file outputTemplate.yml
Resources:
  map-segment-fetcher:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: Lambda Function to fetch the requested map segments
      MemorySize: 128
      Timeout: 3
      Role: AwsRoleForLambda

artifacts:
  files:
    - template.yml
    - outputTemplate.yml
    #https://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html
    #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax
